import AuthProvider from '@/context';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// add all imp seo metatags to following metdata object
export const metadata = {
  title: 'Expense Manager',
  description: 'Generated by create next app chkra ui',
  manifest: {
    name: 'Expense Manager',
    short_name: 'Expense Manager',
    description: 'Generated by create next app',
    start_url: '/',
    background_color: '#ffffff',
    theme_color: '#ffffff',
    display: 'standalone',
    icons: [
      {
        src: '/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.ico" />
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
